---
- name: Installing Nginx,Mariabdb,phpfpm and wordpress
  hosts: [ansible_server]
  remote_user: root 
  become: yes
  roles:
    - mariadb
    - nginx
    - php-fpm
    - wordpress

# environment:
# https://yourproxyip:portno
  
 
