---
- name: Download WordPress
  get_url: url=http://wordpress.org/wordpress-4.6.tar.gz dest=/srv/wordpress-4.6.tar.gz

- name: Extract archive
  command: chdir=/srv/ /bin/tar xvf wordpress-4.6.tar.gz creates=/srv/wordpress

- name: Add group "wordpress"
  group: name=wordpress

- name: Add user "wordpress"
  user: name=wordpress group=wordpress home=/srv/wordpress/

- name: Fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  become: no

#use this only if you have set a password for root or else commit it
- name: Create wpapp database 
  mysql_db:
    name: "{{ wp_db_name }}" 
    login_user: root    
    login_password: "{{mysql_root_password}}" 
    login_host: localhost 
    state: present


#use this to directly create a databse if you hvent set a password for roor
#- name: Create WordPress database
#  mysql_db: name={{ wp_db_name }} state=present 

#use this to create a wordpress databse user if password is set for root
- name: Create user for wordpress db 
  mysql_user: 
    name: "{{ wp_db_user }}" 
    password: "{{ wp_db_password}}" 
    priv: "{{ wp_db_name }}.*:ALL" 
    login_user: root 
    login_password: "{{mysql_root_password}}" 
    state: present

#use this to create a of you haven't created a password for root
#- name: Create WordPress database user
#  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host='localhost' state=present

- name: Copy WordPress config file
  template: src=wp-config.php dest=/srv/wordpress/

- name: Change ownership of WordPress installation
  file: path=/srv/wordpress/ owner=wordpress group=wordpress state=directory recurse=yes

- name: Start php-fpm Service
  service: name=php-fpm state=started enabled=yes
